//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCardGame.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebCardGame.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to class Card {
        ///    constructor(cardIndex) {
        ///        this.RootNode = createElementWithClass(&quot;div&quot;, &quot;Card&quot;);
        ///        this.CardIndex = cardIndex;
        ///
        ///        this.CardLabel = document.createTextNode(&quot;? of ?&quot;);
        ///        this.Button = document.createElement(&quot;button&quot;);
        ///
        ///        this.Action = function (index) { alert(&quot;unset&quot;); };
        ///        var instance = this;
        ///        this.Button.addEventListener(&quot;click&quot;, function () {
        ///            if (instance.Action != null) {
        ///                instance.Action(instance.CardInde [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Card {
            get {
                return ResourceManager.GetString("Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to class CardDisplay {
        ///    constructor(styleClass, id) {
        ///        this.RootNode = createElementWithClassAndId(&quot;div&quot;, styleClass, id);
        ///        this.Slots = [3]; // Array of card slots.
        ///        for (var index = 0; index &lt; 3; ++index) {
        ///            var slot = new CardSlot(index);
        ///            this.Slots[index] = slot;
        ///            this.RootNode.appendChild(this.Slots[index].RootNode);
        ///        }
        ///    }
        ///
        ///    SetupFromArray(cardArray) {
        ///        for (var index = 0; index &lt; 3; ++index) {
        ///            if (cardA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CardDisplay {
            get {
                return ResourceManager.GetString("CardDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to class CardMini {
        ///    constructor(card) {
        ///        this.RootNode = createElementWithClass(&quot;div&quot;, &quot;CardMini&quot;);
        ///        this.Label = document.createTextNode(&quot;&quot;);
        ///        this.RootNode.appendChild(this.Label);
        ///        this.Setup(card);
        ///    }
        ///
        ///    Setup(card) {
        ///        this.Label.textContent = MiniValueLabel[card.Value] + SigilSymbol[card.Sigil];
        ///    }
        ///}.
        /// </summary>
        internal static string CardMini {
            get {
                return ResourceManager.GetString("CardMini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to class CardSlot {
        ///    constructor(index) {
        ///        this.Index = index;
        ///        this.RootNode = createElementWithClass(&quot;div&quot;, &quot;CardSlot&quot;);
        ///        this.CardReceptacle = createElementWithClass(&quot;div&quot;, &quot;CardReceptacle&quot;);
        ///        this.RootNode.appendChild(this.CardReceptacle);
        ///        this.Card = null;
        ///
        ///        this.Button = document.createElement(&quot;button&quot;);
        ///        this.ButtonLabel = document.createTextNode(&quot;_&quot;);
        ///        this.Button.appendChild(this.ButtonLabel);
        ///
        ///        this.Action = function (inde [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CardSlot {
            get {
                return ResourceManager.GetString("CardSlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;FacesData&quot;: [
        ///    [
        ///      [
        ///        &quot; ~~~~~~~~~ &quot;,
        ///        &quot;/ ~~~~~~~ \\&quot;,
        ///        &quot;|          |&quot;,
        ///        &quot;|   O   O  |&quot;,
        ///        &quot;|     U    |&quot;,
        ///        &quot;|   \\___/  |&quot;,
        ///        &quot;\\         /&quot;,
        ///        &quot; ¯¯¯¯¯¯¯¯¯ &quot;
        ///      ]
        ///    ],
        ///    [
        ///      [
        ///        &quot; ~~~~~~~~~ &quot;,
        ///        &quot;/~~~      \\&quot;,
        ///        &quot;|~~        |&quot;,
        ///        &quot;|~  O   O  |&quot;,
        ///        &quot;|   ¯ V ¯  |&quot;,
        ///        &quot;|# |____| #|&quot;,
        ///        &quot;\\#########/&quot;,
        ///        &quot;  ¯¯¯¯¯¯¯¯  &quot;
        ///      ]
        ///    ],
        ///    [
        ///      [
        ///        &quot; _   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Config {
            get {
                return ResourceManager.GetString("Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to class Deck {
        ///    constructor() {
        ///        this.RootNode = createElementWithClass(&quot;div&quot;, &quot;Deck&quot;);
        ///        var div = createElementWithClass(&quot;div&quot;);
        ///        var label = document.createTextNode(&quot;Deck&quot;);
        ///        div.appendChild(label);
        ///        this.RootNode.appendChild(div);
        ///
        ///        div = createElementWithClass(&quot;div&quot;)
        ///        this.CardCountLabel = document.createTextNode(&quot;&quot;);
        ///        div.appendChild(this.CardCountLabel);
        ///        this.RootNode.appendChild(div);
        ///    }
        ///
        ///    Setup(gameState) {
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Deck {
            get {
                return ResourceManager.GetString("Deck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to class DiscardPile {
        ///    constructor() {
        ///        this.RootNode = createElementWithClass(&quot;div&quot;, &quot;Deck&quot;);
        ///        var div = createElementWithClass(&quot;div&quot;);
        ///        var label = document.createTextNode(&quot;Discard&quot;);
        ///        div.appendChild(label);
        ///        this.RootNode.appendChild(div);
        ///
        ///        div = createElementWithClass(&quot;div&quot;)
        ///        this.CardCountLabel = document.createTextNode(&quot;&quot;);
        ///        div.appendChild(this.CardCountLabel);
        ///        this.RootNode.appendChild(div);
        ///    }
        ///
        ///    Setup(gameState)  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DiscardPile {
            get {
                return ResourceManager.GetString("DiscardPile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to class EndGame {
        ///    constructor() {
        ///        this.RootNode = createElementWithClass(&quot;table&quot;,&quot;EndGame&quot;);
        ///
        ///        this.EndGameLabel = document.createTextNode(&quot;Game Ended&quot;);
        ///        var col = document.createElement(&quot;th&quot;);
        ///        var row = document.createElement(&quot;tr&quot;);
        ///        col.appendChild(row);
        ///        row.appendChild(this.EndGameLabel);
        ///        this.RootNode.appendChild(col);
        ///        this.WinningPlayerLabel = document.createTextNode(&quot;Player ? Win&quot;);
        ///        row = document.createElement(&quot;tr&quot;);
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EndGame {
            get {
                return ResourceManager.GetString("EndGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to class Face {
        ///    constructor() {
        ///        this.RootNode = createElementWithClass(&quot;div&quot;, &quot;Face&quot;);
        ///        this.Button = document.createElement(&quot;button&quot;);
        ///        this.Div = document.createElement(&quot;div&quot;);
        ///
        ///        this.Rows = [];
        ///        this.Pres = [];
        ///        for (var index = 0; index &lt; 8; ++index) {
        ///            this.Pres[index] = document.createElement(&quot;pre&quot;);
        ///            this.Rows[index] = document.createTextNode(&quot;&quot;);
        ///            this.Pres[index].appendChild(this.Rows[index]);
        ///        }
        ///
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Face {
            get {
                return ResourceManager.GetString("Face", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to class FaceCollection {
        ///    constructor() {
        ///        this.RootNode = createElementWithClass(&quot;div&quot;, &quot;FaceCollection&quot;);
        ///
        ///        const xmlhttp = new XMLHttpRequest();
        ///        let instance = this;
        ///        xmlhttp.onload = function () {
        ///            const myObj = JSON.parse(xmlhttp.responseText);
        ///            instance.FacesData = myObj.FacesData;
        ///            instance.OnFaceLoaded();
        ///        }
        ///
        ///        xmlhttp.open(&quot;POST&quot;, &quot;Config.json&quot;);
        ///        xmlhttp.setRequestHeader(&quot;Content-type&quot;, &quot;application/x-w [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FaceCollection {
            get {
                return ResourceManager.GetString("FaceCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!doctype html&gt;
        ///&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;
        ///&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;Style.css&quot; /&gt;
        ///
        ///&lt;div id=mainContainer&gt;
        ///    &lt;h2&gt;Two Players Solitaire&lt;/h2&gt;
        ///    &lt;div&gt;
        ///        &lt;div id=playArea&gt;&lt;/div&gt;
        ///    &lt;/div&gt;
        ///&lt;/div&gt;
        ///
        ///&lt;div id=debugArea&gt;
        ///    &lt;button onclick=&quot;toggleDebug()&quot;&gt; &lt;/button&gt;
        ///    &lt;div id=debugOutput&gt;&lt;/div&gt;
        ///&lt;/div&gt;
        ///
        ///&lt;div id=&quot;signature&quot;&gt;
        ///    Made by &lt;a href=&quot;https://antonmakesgames.itch.io/&quot; target=&quot;_blank&quot; rel=&quot;noopener noreferrer&quot;&gt;AntonMake [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GameIndex {
            get {
                return ResourceManager.GetString("GameIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to class GameInfo {
        ///    constructor() {
        ///        this.RootNode = createElementWithClass(&quot;div&quot;, &quot;GeneralInfoContainer&quot;);
        ///
        ///        this.Deck = new Deck();
        ///        this.RootNode.appendChild(this.Deck.RootNode);
        ///
        ///        this.DiscardPile = new DiscardPile();
        ///        this.RootNode.appendChild(this.DiscardPile.RootNode);
        ///    }
        ///
        ///    Setup(playerIndex, gameState) {
        ///        this.Deck.Setup(gameState);
        ///        this.DiscardPile.Setup(gameState);
        ///    }
        ///}.
        /// </summary>
        internal static string GameInfo {
            get {
                return ResourceManager.GetString("GameInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to const GameStateID = [
        ///    &quot;Initialize&quot;,
        ///    &quot;Playing&quot;,
        ///    &quot;Transitioning&quot;,
        ///    &quot;EndGame&quot;,
        ///    &quot;Unkown&quot;];
        ///
        ///const SigilLabel = [
        ///    &quot;Spade&quot;,
        ///    &quot;Club&quot;,
        ///    &quot;Heart&quot;,
        ///    &quot;Diamond&quot;];
        ///
        ///const SigilSymbol = [
        ///    &quot;♠&quot;,
        ///    &quot;♣&quot;,
        ///    &quot;♥&quot;,
        ///    &quot;♦&quot;];
        ///
        ///const ValueLabel = [
        ///    &quot;Ace&quot;,
        ///    &quot;2&quot;,
        ///    &quot;3&quot;,
        ///    &quot;4&quot;,
        ///    &quot;5&quot;,
        ///    &quot;6&quot;,
        ///    &quot;7&quot;,
        ///    &quot;8&quot;,
        ///    &quot;9&quot;,
        ///    &quot;10&quot;,
        ///];
        ///
        ///const MiniValueLabel = [
        ///    &quot;1&quot;,
        ///    &quot;2&quot;,
        ///    &quot;3&quot;,
        ///    &quot;4&quot;,
        ///    &quot;5&quot;,
        ///    &quot;6&quot;,
        ///    &quot;7&quot;,
        ///    &quot;8&quot;,
        ///    &quot;9&quot;,
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MultiplayerSolitaire {
            get {
                return ResourceManager.GetString("MultiplayerSolitaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     class Opponent {
        ///        constructor() {
        ///            this.RootNode = createElementWithClass(&quot;table&quot;, &quot;otherPlayer&quot;);
        ///
        ///            var row = document.createElement(&quot;tr&quot;);
        ///            this.RootNode.appendChild(row);
        ///            this.PlayerLabel = document.createTextNode(&quot;Player ?&quot;);
        ///            row.appendChild(this.PlayerLabel);
        ///
        ///            this.ScoreLabel = document.createTextNode(&quot;Score : &quot;);
        ///            this.HealthLabel = document.createTextNode(&quot;Health : &quot;);
        ///            this.PairBulletLabe [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Opponent {
            get {
                return ResourceManager.GetString("Opponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to class Player {
        ///    constructor(id, labelName) {
        ///        this.Header = new PlayerHeader(id, labelName);
        ///        this.Header.Face.SetInteractable(false);
        ///        this.PlayerStats = new PlayerStats(id);
        ///        this.Board = new CardDisplay(&quot;PlayerBoard&quot;, id);
        ///        this.Hand = new CardDisplay(&quot;PlayerHand&quot;, id);
        ///        this.HasHand = false;
        ///
        ///        this.RootNode = createElementWithClass(&quot;table&quot;, &quot;player&quot;);
        ///        this.PlayerLabel = document.createTextNode(&quot;Player &quot; + localPlayerIndex);
        ///        v [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Player {
            get {
                return ResourceManager.GetString("Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to class PlayerSlots {
        ///    constructor() {
        ///        this.RootNode = document.createElement(&quot;table&quot;);
        ///        this.Buttons = [];
        ///        var row = document.createElement(&quot;tr&quot;);
        ///        this.RootNode.appendChild(row);
        ///
        ///        this.PoolSize = 10;
        ///        for (var index = 0; index &lt; this.PoolSize; ++index) {
        ///            this.Buttons[index] = document.createElement(&quot;button&quot;);
        ///            var label = document.createTextNode(&quot;Player &quot; + (index + 1));
        ///            this.Buttons[index].appendChild(label);
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PlayerSlots {
            get {
                return ResourceManager.GetString("PlayerSlots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to class PooledLogTable {
        ///    constructor() {
        ///        this.RootNode = createElementWithClass(&quot;Div&quot;, &quot;GameLog&quot;);
        ///        this.PoolSize = 15;
        ///        this.Pool = [];
        ///        for (var index = 0; index &lt; this.PoolSize; ++index)
        ///        {
        ///            this.Pool[index] = createElementWithClass(&quot;div&quot;, &quot;LogEntry&quot;);
        ///            this.Pool[index].Label = document.createTextNode(&quot;&quot;);
        ///        }
        ///
        ///        this.Cursor = 0;
        ///    }
        ///
        ///    Clear() {
        ///        clearChilds(this.RootNode);
        ///        this.Cursor = 0;
        ///    }        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PooledLogTable {
            get {
                return ResourceManager.GetString("PooledLogTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to body {
        ///    font-family: &quot;Times New Roman&quot;, Times, serif;
        ///}
        ///
        ///#mainContainer {
        ///    display: flex;
        ///    flex-flow: column;
        ///    justify-content: center;
        ///    text-align: center;
        ///}
        ///
        ///#playArea {
        ///    width: 500pt;
        ///    display: inline-grid;
        ///    grid-gap: 5pt 10pt;
        ///    margin-right: 200pt;
        ///}
        ///
        ///.PlayerHeader {
        ///    grid-column: 2;
        ///    display: flex;
        ///    flex-direction: row;
        ///    align-items: center;
        ///    justify-content: center;
        ///    gap: 30pt;
        ///}
        ///
        ///.PlayerStats {
        ///    grid-column: 2;
        ///    display:  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Style {
            get {
                return ResourceManager.GetString("Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function CreateWebSocket() {
        ///    console.log(gameWebSocketUrl);
        ///    websocket = new WebSocket(gameWebSocketUrl);
        ///
        ///    websocket.onopen = function (e) {
        ///        isConnected = true;
        ///        writeToScreen(&quot;CONNECTED&quot;);
        ///        var requestFaces = &apos;{ &quot;OrderType&quot;: &quot;RequestPlayerFaces&quot; }&apos;;
        ///        DoSend(requestFaces);
        ///    };
        ///
        ///    websocket.onclose = function (e) {
        ///        writeToScreen(&quot;DISCONNECTED&quot;);
        ///    };
        ///
        ///    websocket.onmessage = RecieveWebSocketMessage;
        ///
        ///    websocket.onerror = function (e [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WebSocket {
            get {
                return ResourceManager.GetString("WebSocket", resourceCulture);
            }
        }
    }
}
